# Скрипт для проверки localStorage данных
Write-Host "Откройте браузер и выполните следующие команды в консоли:"
Write-Host ""
Write-Host "// Проверка selectedChatIds"
Write-Host "console.log('selectedChatIds:', localStorage.getItem('selectedChatIds'));"
Write-Host ""
Write-Host "// Проверка всех ключей"
Write-Host "Object.keys(localStorage).forEach(key => {"
Write-Host "  const value = localStorage.getItem(key);"
Write-Host "  console.log(key + ':', value ? (value.length > 100 ? value.substring(0, 100) + '...' : value) : 'null');"
Write-Host "});"
Write-Host ""
Write-Host "// Очистка selectedChatIds если нужно"
Write-Host "// localStorage.removeItem('selectedChatIds');"
Write-Host ""
Write-Host "// Установка правильного формата selectedChatIds"
Write-Host "// localStorage.setItem('selectedChatIds', JSON.stringify(['chat1', 'chat2']));"