directories:
  output: electron-dist
  buildResources: build
appId: com.genai.telegram-lead-scanner
productName: Telegram Lead Scanner
files:
  - filter:
      - dist/**/*
      - backend/**/*
      - main.js
      - package.json
      - node_modules/**/*
extraResources:
  - from: backend
    to: backend
    filter:
      - '**/*'
      - '!node_modules'
win:
  target: nsis
  icon: public/vite.svg
  sign: false
mac:
  target: dmg
  icon: public/vite.svg
linux:
  target: AppImage
  icon: public/vite.svg
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 28.3.3
